title: Unashamed Games
description: >-
  Unashamed Games is a wholesome iOS app with classic games like
  Tic-Tac-Toe, Checkers, Solitaire, and Sudoku. Free to play with
  limited respectful ads and an option to remove ads.
url: https://unashamedgames.com
baseurl: ""
logo: /assets/brand/wordmark.png

social:
  name: Unashamed Games

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics_id: G-7MTF8FSV4X
